backend:
  name: github
  branch: main
  repo: sally-nilsson.github.io/Test_hemsida_nyheter

media_folder: "assets/uploads"
public_folder: "/assets/uploads"

collections:
  - name: "data"
    label: "Innehåll"
    files:
      - name: "all_content"
        label: "Hantera Innehåll"
        file: "content.json"
        fields:
          - name: "news"
            label: "Nyheter"
            widget: "list"
            fields:
              - {label: "Titel", name: "title", widget: "string"}
              - {label: "Datum", name: "date", widget: "datetime"}
              - {label: "Text", name: "body", widget: "markdown"}
          - name: "protokoll"
            label: "Mötesprotokoll"
            widget: "list"
            fields:
              - {label: "Mötesnamn", name: "title", widget: "string"}
              - {label: "Datum", name: "date", widget: "date"}
              - {label: "Ladda upp PDF", name: "pdf", widget: "file"}
