backend:
  name: git-gateway
  branch: main

media_folder: "assets/uploads"
public_folder: "/assets/uploads"

collections:
  - name: "data"
    label: "Innehåll"
    files:
      - name: "all_content"
        label: "Hantera Innehåll"
        file: "content.json" # Vi skriver direkt till denna fil
        fields:
          # Lista för Nyheter
          - name: "news"
            label: "Nyheter"
            widget: "list"
            fields:
              - {label: "Titel", name: "title", widget: "string"}
              - {label: "Datum", name: "date", widget: "datetime"}
              - {label: "Text", name: "body", widget: "markdown"}

          # Lista för Protokoll
          - name: "protokoll"
            label: "Mötesprotokoll"
            widget: "list"
            fields:
              - {label: "Mötesnamn", name: "title", widget: "string"}
              - {label: "Datum", name: "date", widget: "date"}
              - {label: "Ladda upp PDF", name: "pdf", widget: "file"}